#![allow(dead_code)]

// This file is auto-generated by scripts/generate-bridge-contracts.mjs.
// Do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BridgeFieldKind {
    String,
    Boolean,
    Int,
    StringArray,
    Object,
}

#[derive(Debug, Clone, Copy)]
pub struct BridgeFieldContract {
    pub name: &'static str,
    pub kind: BridgeFieldKind,
}

#[derive(Debug, Clone, Copy)]
pub struct BridgeSectionContract {
    pub section: Option<&'static str>,
    pub fields: &'static [BridgeFieldContract],
}

pub mod migoto_form {
    pub const ENABLED: &str = "enabled";
    pub const IMPORTER: &str = "importer";
    pub const USE_HOOK: &str = "use_hook";
    pub const ENFORCE_RENDERING: &str = "enforce_rendering";
    pub const ENABLE_HUNTING: &str = "enable_hunting";
    pub const DUMP_SHADERS: &str = "dump_shaders";
    pub const MUTE_WARNINGS: &str = "mute_warnings";
    pub const CALLS_LOGGING: &str = "calls_logging";
    pub const DEBUG_LOGGING: &str = "debug_logging";
    pub const UNSAFE_MODE: &str = "unsafe_mode";
    pub const PROCESS_TIMEOUT: &str = "process_timeout";
    pub const MIGOTO_PATH: &str = "migoto_path";
    pub const IMPORTER_FOLDER: &str = "importer_folder";
    pub const MOD_FOLDER: &str = "mod_folder";
    pub const SHADER_FIXES_FOLDER: &str = "shader_fixes_folder";
    pub const D3DX_INI_PATH: &str = "d3dx_ini_path";
    pub const BRIDGE_EXE_PATH: &str = "bridge_exe_path";
    pub const START_ARGS: &str = "start_args";
    pub const PROCESS_START_METHOD: &str = "process_start_method";
    pub const PROCESS_PRIORITY: &str = "process_priority";
    pub const XXMI_DLL_INIT_DELAY: &str = "xxmi_dll_init_delay";
    pub const EXTRA_LIBRARIES_ENABLED: &str = "extra_libraries_enabled";
    pub const EXTRA_LIBRARIES_PATHS: &str = "extra_libraries_paths";
    pub const CUSTOM_LAUNCH_ENABLED: &str = "custom_launch_enabled";
    pub const CUSTOM_LAUNCH_CMD: &str = "custom_launch_cmd";
    pub const CUSTOM_LAUNCH_INJECT_MODE: &str = "custom_launch_inject_mode";
    pub const PRE_LAUNCH_ENABLED: &str = "pre_launch_enabled";
    pub const PRE_LAUNCH_CMD: &str = "pre_launch_cmd";
    pub const PRE_LAUNCH_WAIT: &str = "pre_launch_wait";
    pub const POST_LOAD_ENABLED: &str = "post_load_enabled";
    pub const POST_LOAD_CMD: &str = "post_load_cmd";
    pub const POST_LOAD_WAIT: &str = "post_load_wait";
    pub const WWMI_CONFIGURE_GAME: &str = "wwmi_configure_game";
    pub const WWMI_UNLOCK_FPS: &str = "wwmi_unlock_fps";
    pub const WWMI_PERF_TWEAKS: &str = "wwmi_perf_tweaks";
    pub const WWMI_DISABLE_WOUNDED_FX: &str = "wwmi_disable_wounded_fx";
}

pub mod sections {
    pub const PATHS: &str = "paths";
    pub const GAME: &str = "game";
    pub const MIGOTO: &str = "migoto";
    pub const D3DX_INI: &str = "d3dx_ini";
    pub const SIGNATURES: &str = "signatures";
    pub const EXTRA_LIBRARIES: &str = "extra_libraries";
    pub const CUSTOM_LAUNCH: &str = "custom_launch";
    pub const PRE_LAUNCH: &str = "pre_launch";
    pub const POST_LOAD: &str = "post_load";
    pub const JADEITE: &str = "jadeite";
}

pub mod root {
    pub const SCHEMA_VERSION: &str = "schemaVersion";
    pub const IMPORTER: &str = "importer";
}

pub mod paths {
    pub const APP_ROOT: &str = "app_root";
    pub const IMPORTER_FOLDER: &str = "importer_folder";
    pub const PACKAGES_FOLDER: &str = "packages_folder";
    pub const GAME_FOLDER: &str = "game_folder";
    pub const GAME_EXE: &str = "game_exe";
    pub const CACHE_FOLDER: &str = "cache_folder";
    pub const MOD_FOLDER: &str = "mod_folder";
    pub const SHADER_FIXES_FOLDER: &str = "shader_fixes_folder";
    pub const D3DX_INI: &str = "d3dx_ini";
}

pub mod game {
    pub const START_EXE: &str = "start_exe";
    pub const START_ARGS: &str = "start_args";
    pub const WORK_DIR: &str = "work_dir";
    pub const PROCESS_NAME: &str = "process_name";
    pub const PROCESS_START_METHOD: &str = "process_start_method";
    pub const PROCESS_PRIORITY: &str = "process_priority";
    pub const PROCESS_TIMEOUT: &str = "process_timeout";
}

pub mod migoto {
    pub const USE_HOOK: &str = "use_hook";
    pub const USE_DLL_DROP: &str = "use_dll_drop";
    pub const ENFORCE_RENDERING: &str = "enforce_rendering";
    pub const ENABLE_HUNTING: &str = "enable_hunting";
    pub const DUMP_SHADERS: &str = "dump_shaders";
    pub const MUTE_WARNINGS: &str = "mute_warnings";
    pub const CALLS_LOGGING: &str = "calls_logging";
    pub const DEBUG_LOGGING: &str = "debug_logging";
    pub const UNSAFE_MODE: &str = "unsafe_mode";
    pub const XXMI_DLL_INIT_DELAY: &str = "xxmi_dll_init_delay";
}

pub mod d3dx_ini {}

pub mod signatures {
    pub const XXMI_PUBLIC_KEY: &str = "xxmi_public_key";
    pub const DEPLOYED_MIGOTO_SIGNATURES: &str = "deployed_migoto_signatures";
}

pub mod extra_libraries {
    pub const ENABLED: &str = "enabled";
    pub const PATHS: &str = "paths";
}

pub mod custom_launch {
    pub const ENABLED: &str = "enabled";
    pub const CMD: &str = "cmd";
    pub const INJECT_MODE: &str = "inject_mode";
}

pub mod pre_launch {
    pub const ENABLED: &str = "enabled";
    pub const CMD: &str = "cmd";
    pub const WAIT: &str = "wait";
}

pub mod post_load {
    pub const ENABLED: &str = "enabled";
    pub const CMD: &str = "cmd";
    pub const WAIT: &str = "wait";
}

pub mod jadeite {
    pub const ENABLED: &str = "enabled";
    pub const EXE_PATH: &str = "exe_path";
}

pub const ROOT_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: root::SCHEMA_VERSION,
        kind: BridgeFieldKind::Int,
    },
    BridgeFieldContract {
        name: root::IMPORTER,
        kind: BridgeFieldKind::String,
    },
];

pub const PATHS_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: paths::APP_ROOT,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::IMPORTER_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::PACKAGES_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::GAME_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::GAME_EXE,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::CACHE_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::MOD_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::SHADER_FIXES_FOLDER,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: paths::D3DX_INI,
        kind: BridgeFieldKind::String,
    },
];

pub const GAME_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: game::START_EXE,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: game::START_ARGS,
        kind: BridgeFieldKind::StringArray,
    },
    BridgeFieldContract {
        name: game::WORK_DIR,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: game::PROCESS_NAME,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: game::PROCESS_START_METHOD,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: game::PROCESS_PRIORITY,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: game::PROCESS_TIMEOUT,
        kind: BridgeFieldKind::Int,
    },
];

pub const MIGOTO_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: migoto::USE_HOOK,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::USE_DLL_DROP,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::ENFORCE_RENDERING,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::ENABLE_HUNTING,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::DUMP_SHADERS,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::MUTE_WARNINGS,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::CALLS_LOGGING,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::DEBUG_LOGGING,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::UNSAFE_MODE,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: migoto::XXMI_DLL_INIT_DELAY,
        kind: BridgeFieldKind::Int,
    },
];

pub const D3DX_INI_FIELDS: &[BridgeFieldContract] = &[BridgeFieldContract {
    name: "d3dx_ini",
    kind: BridgeFieldKind::Object,
}];

pub const SIGNATURES_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: signatures::XXMI_PUBLIC_KEY,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: signatures::DEPLOYED_MIGOTO_SIGNATURES,
        kind: BridgeFieldKind::Object,
    },
];

pub const EXTRA_LIBRARIES_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: extra_libraries::ENABLED,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: extra_libraries::PATHS,
        kind: BridgeFieldKind::StringArray,
    },
];

pub const CUSTOM_LAUNCH_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: custom_launch::ENABLED,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: custom_launch::CMD,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: custom_launch::INJECT_MODE,
        kind: BridgeFieldKind::String,
    },
];

pub const PRE_LAUNCH_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: pre_launch::ENABLED,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: pre_launch::CMD,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: pre_launch::WAIT,
        kind: BridgeFieldKind::Boolean,
    },
];

pub const POST_LOAD_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: post_load::ENABLED,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: post_load::CMD,
        kind: BridgeFieldKind::String,
    },
    BridgeFieldContract {
        name: post_load::WAIT,
        kind: BridgeFieldKind::Boolean,
    },
];

pub const JADEITE_FIELDS: &[BridgeFieldContract] = &[
    BridgeFieldContract {
        name: jadeite::ENABLED,
        kind: BridgeFieldKind::Boolean,
    },
    BridgeFieldContract {
        name: jadeite::EXE_PATH,
        kind: BridgeFieldKind::String,
    },
];

pub const BRIDGE_CONFIG_CONTRACT: &[BridgeSectionContract] = &[
    BridgeSectionContract {
        section: None,
        fields: ROOT_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::PATHS),
        fields: PATHS_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::GAME),
        fields: GAME_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::MIGOTO),
        fields: MIGOTO_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::D3DX_INI),
        fields: D3DX_INI_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::SIGNATURES),
        fields: SIGNATURES_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::EXTRA_LIBRARIES),
        fields: EXTRA_LIBRARIES_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::CUSTOM_LAUNCH),
        fields: CUSTOM_LAUNCH_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::PRE_LAUNCH),
        fields: PRE_LAUNCH_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::POST_LOAD),
        fields: POST_LOAD_FIELDS,
    },
    BridgeSectionContract {
        section: Some(sections::JADEITE),
        fields: JADEITE_FIELDS,
    },
];
