#pragma once

// This file is auto-generated by scripts/generate-bridge-contracts.mjs.
// Do not edit by hand.

#include <cstddef>

namespace bridge_contract {

enum class FieldKind {
    String,
    Boolean,
    Int,
    StringArray,
    Object,
};

struct FieldContract {
    const char* name;
    FieldKind kind;
};

struct SectionContract {
    const char* name;
    const FieldContract* fields;
    std::size_t field_count;
};

namespace migoto_form {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kImporter[] = "importer";
inline constexpr char kUseHook[] = "use_hook";
inline constexpr char kEnforceRendering[] = "enforce_rendering";
inline constexpr char kEnableHunting[] = "enable_hunting";
inline constexpr char kDumpShaders[] = "dump_shaders";
inline constexpr char kMuteWarnings[] = "mute_warnings";
inline constexpr char kCallsLogging[] = "calls_logging";
inline constexpr char kDebugLogging[] = "debug_logging";
inline constexpr char kUnsafeMode[] = "unsafe_mode";
inline constexpr char kProcessTimeout[] = "process_timeout";
inline constexpr char kMigotoPath[] = "migoto_path";
inline constexpr char kImporterFolder[] = "importer_folder";
inline constexpr char kModFolder[] = "mod_folder";
inline constexpr char kShaderFixesFolder[] = "shader_fixes_folder";
inline constexpr char kD3dxIniPath[] = "d3dx_ini_path";
inline constexpr char kBridgeExePath[] = "bridge_exe_path";
inline constexpr char kStartArgs[] = "start_args";
inline constexpr char kProcessStartMethod[] = "process_start_method";
inline constexpr char kProcessPriority[] = "process_priority";
inline constexpr char kXxmiDllInitDelay[] = "xxmi_dll_init_delay";
inline constexpr char kExtraLibrariesEnabled[] = "extra_libraries_enabled";
inline constexpr char kExtraLibrariesPaths[] = "extra_libraries_paths";
inline constexpr char kCustomLaunchEnabled[] = "custom_launch_enabled";
inline constexpr char kCustomLaunchCmd[] = "custom_launch_cmd";
inline constexpr char kCustomLaunchInjectMode[] = "custom_launch_inject_mode";
inline constexpr char kPreLaunchEnabled[] = "pre_launch_enabled";
inline constexpr char kPreLaunchCmd[] = "pre_launch_cmd";
inline constexpr char kPreLaunchWait[] = "pre_launch_wait";
inline constexpr char kPostLoadEnabled[] = "post_load_enabled";
inline constexpr char kPostLoadCmd[] = "post_load_cmd";
inline constexpr char kPostLoadWait[] = "post_load_wait";
inline constexpr char kWwmiConfigureGame[] = "wwmi_configure_game";
inline constexpr char kWwmiUnlockFps[] = "wwmi_unlock_fps";
inline constexpr char kWwmiPerfTweaks[] = "wwmi_perf_tweaks";
inline constexpr char kWwmiDisableWoundedFx[] = "wwmi_disable_wounded_fx";
}

namespace sections {
inline constexpr char kPaths[] = "paths";
inline constexpr char kGame[] = "game";
inline constexpr char kMigoto[] = "migoto";
inline constexpr char kD3dxIni[] = "d3dx_ini";
inline constexpr char kSignatures[] = "signatures";
inline constexpr char kExtraLibraries[] = "extra_libraries";
inline constexpr char kCustomLaunch[] = "custom_launch";
inline constexpr char kPreLaunch[] = "pre_launch";
inline constexpr char kPostLoad[] = "post_load";
inline constexpr char kJadeite[] = "jadeite";
}

namespace root {
inline constexpr char kSchemaVersion[] = "schemaVersion";
inline constexpr char kImporter[] = "importer";
}

namespace paths {
inline constexpr char kAppRoot[] = "app_root";
inline constexpr char kImporterFolder[] = "importer_folder";
inline constexpr char kPackagesFolder[] = "packages_folder";
inline constexpr char kGameFolder[] = "game_folder";
inline constexpr char kGameExe[] = "game_exe";
inline constexpr char kCacheFolder[] = "cache_folder";
inline constexpr char kModFolder[] = "mod_folder";
inline constexpr char kShaderFixesFolder[] = "shader_fixes_folder";
inline constexpr char kD3dxIni[] = "d3dx_ini";
}

namespace game {
inline constexpr char kStartExe[] = "start_exe";
inline constexpr char kStartArgs[] = "start_args";
inline constexpr char kWorkDir[] = "work_dir";
inline constexpr char kProcessName[] = "process_name";
inline constexpr char kProcessStartMethod[] = "process_start_method";
inline constexpr char kProcessPriority[] = "process_priority";
inline constexpr char kProcessTimeout[] = "process_timeout";
}

namespace migoto {
inline constexpr char kUseHook[] = "use_hook";
inline constexpr char kUseDllDrop[] = "use_dll_drop";
inline constexpr char kEnforceRendering[] = "enforce_rendering";
inline constexpr char kEnableHunting[] = "enable_hunting";
inline constexpr char kDumpShaders[] = "dump_shaders";
inline constexpr char kMuteWarnings[] = "mute_warnings";
inline constexpr char kCallsLogging[] = "calls_logging";
inline constexpr char kDebugLogging[] = "debug_logging";
inline constexpr char kUnsafeMode[] = "unsafe_mode";
inline constexpr char kXxmiDllInitDelay[] = "xxmi_dll_init_delay";
}

namespace d3dx_ini {

}

namespace signatures {
inline constexpr char kXxmiPublicKey[] = "xxmi_public_key";
inline constexpr char kDeployedMigotoSignatures[] = "deployed_migoto_signatures";
}

namespace extra_libraries {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kPaths[] = "paths";
}

namespace custom_launch {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kCmd[] = "cmd";
inline constexpr char kInjectMode[] = "inject_mode";
}

namespace pre_launch {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kCmd[] = "cmd";
inline constexpr char kWait[] = "wait";
}

namespace post_load {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kCmd[] = "cmd";
inline constexpr char kWait[] = "wait";
}

namespace jadeite {
inline constexpr char kEnabled[] = "enabled";
inline constexpr char kExePath[] = "exe_path";
}

inline constexpr FieldContract kRootFields[] = {
    FieldContract{root::kSchemaVersion, FieldKind::Int},
    FieldContract{root::kImporter, FieldKind::String},
};

inline constexpr FieldContract kPathsFields[] = {
    FieldContract{paths::kAppRoot, FieldKind::String},
    FieldContract{paths::kImporterFolder, FieldKind::String},
    FieldContract{paths::kPackagesFolder, FieldKind::String},
    FieldContract{paths::kGameFolder, FieldKind::String},
    FieldContract{paths::kGameExe, FieldKind::String},
    FieldContract{paths::kCacheFolder, FieldKind::String},
    FieldContract{paths::kModFolder, FieldKind::String},
    FieldContract{paths::kShaderFixesFolder, FieldKind::String},
    FieldContract{paths::kD3dxIni, FieldKind::String},
};

inline constexpr FieldContract kGameFields[] = {
    FieldContract{game::kStartExe, FieldKind::String},
    FieldContract{game::kStartArgs, FieldKind::StringArray},
    FieldContract{game::kWorkDir, FieldKind::String},
    FieldContract{game::kProcessName, FieldKind::String},
    FieldContract{game::kProcessStartMethod, FieldKind::String},
    FieldContract{game::kProcessPriority, FieldKind::String},
    FieldContract{game::kProcessTimeout, FieldKind::Int},
};

inline constexpr FieldContract kMigotoFields[] = {
    FieldContract{migoto::kUseHook, FieldKind::Boolean},
    FieldContract{migoto::kUseDllDrop, FieldKind::Boolean},
    FieldContract{migoto::kEnforceRendering, FieldKind::Boolean},
    FieldContract{migoto::kEnableHunting, FieldKind::Boolean},
    FieldContract{migoto::kDumpShaders, FieldKind::Boolean},
    FieldContract{migoto::kMuteWarnings, FieldKind::Boolean},
    FieldContract{migoto::kCallsLogging, FieldKind::Boolean},
    FieldContract{migoto::kDebugLogging, FieldKind::Boolean},
    FieldContract{migoto::kUnsafeMode, FieldKind::Boolean},
    FieldContract{migoto::kXxmiDllInitDelay, FieldKind::Int},
};

inline constexpr FieldContract kD3dxIniFields[] = {
    FieldContract{"d3dx_ini", FieldKind::Object},
};

inline constexpr FieldContract kSignaturesFields[] = {
    FieldContract{signatures::kXxmiPublicKey, FieldKind::String},
    FieldContract{signatures::kDeployedMigotoSignatures, FieldKind::Object},
};

inline constexpr FieldContract kExtraLibrariesFields[] = {
    FieldContract{extra_libraries::kEnabled, FieldKind::Boolean},
    FieldContract{extra_libraries::kPaths, FieldKind::StringArray},
};

inline constexpr FieldContract kCustomLaunchFields[] = {
    FieldContract{custom_launch::kEnabled, FieldKind::Boolean},
    FieldContract{custom_launch::kCmd, FieldKind::String},
    FieldContract{custom_launch::kInjectMode, FieldKind::String},
};

inline constexpr FieldContract kPreLaunchFields[] = {
    FieldContract{pre_launch::kEnabled, FieldKind::Boolean},
    FieldContract{pre_launch::kCmd, FieldKind::String},
    FieldContract{pre_launch::kWait, FieldKind::Boolean},
};

inline constexpr FieldContract kPostLoadFields[] = {
    FieldContract{post_load::kEnabled, FieldKind::Boolean},
    FieldContract{post_load::kCmd, FieldKind::String},
    FieldContract{post_load::kWait, FieldKind::Boolean},
};

inline constexpr FieldContract kJadeiteFields[] = {
    FieldContract{jadeite::kEnabled, FieldKind::Boolean},
    FieldContract{jadeite::kExePath, FieldKind::String},
};

inline constexpr SectionContract kBridgeConfigContract[] = {
    SectionContract{nullptr, kRootFields, sizeof(kRootFields) / sizeof(FieldContract)},
    SectionContract{sections::kPaths, kPathsFields, sizeof(kPathsFields) / sizeof(FieldContract)},
    SectionContract{sections::kGame, kGameFields, sizeof(kGameFields) / sizeof(FieldContract)},
    SectionContract{sections::kMigoto, kMigotoFields, sizeof(kMigotoFields) / sizeof(FieldContract)},
    SectionContract{sections::kD3dxIni, kD3dxIniFields, sizeof(kD3dxIniFields) / sizeof(FieldContract)},
    SectionContract{sections::kSignatures, kSignaturesFields, sizeof(kSignaturesFields) / sizeof(FieldContract)},
    SectionContract{sections::kExtraLibraries, kExtraLibrariesFields, sizeof(kExtraLibrariesFields) / sizeof(FieldContract)},
    SectionContract{sections::kCustomLaunch, kCustomLaunchFields, sizeof(kCustomLaunchFields) / sizeof(FieldContract)},
    SectionContract{sections::kPreLaunch, kPreLaunchFields, sizeof(kPreLaunchFields) / sizeof(FieldContract)},
    SectionContract{sections::kPostLoad, kPostLoadFields, sizeof(kPostLoadFields) / sizeof(FieldContract)},
    SectionContract{sections::kJadeite, kJadeiteFields, sizeof(kJadeiteFields) / sizeof(FieldContract)},
};

inline constexpr std::size_t kBridgeConfigContractCount =
    sizeof(kBridgeConfigContract) / sizeof(SectionContract);

} // namespace bridge_contract
