#pragma once

#include <string>
#include <vector>
#include <map>

namespace bridge {

// All data comes from bridge-config.json generated by the Linux Tauri frontend.
// Nothing is hardcoded — the frontend tells us:
//   - Which game, which exe, which container
//   - Where the 3DMigoto importer folder is (each game has its own independent folder)
//   - All injection and configuration parameters
//
// Per-game isolation: each game has its own importer_folder, packages_folder,
// d3dx.ini, Mods/, ShaderFixes/, etc. Modifying one game never affects another.

struct PathsConfig {
    std::wstring app_root;          // SSMT4-Linux root (Windows path inside container)
    std::wstring importer_folder;   // Per-game 3DMigoto folder (e.g. Z:\...\WWMI)
    std::wstring packages_folder;   // Per-game packages (e.g. Z:\...\Packages\XXMI)
    std::wstring game_folder;       // Game installation folder
    std::wstring game_exe;          // Game executable name (e.g. "Client-Win64-Shipping.exe")
    std::wstring cache_folder;      // Cache folder for mod optimizer etc.
};

struct GameConfig {
    std::wstring start_exe;         // Executable to launch (may differ from game_exe)
    std::vector<std::wstring> start_args;  // Launch arguments (e.g. ["-dx11"])
    std::wstring work_dir;          // Working directory for the process
    std::wstring process_name;      // Process name to track (e.g. "Client-Win64-Shipping.exe")
    std::string process_start_method; // "Native", "Shell", or "Manual"
    std::string process_priority;     // "Normal", "High", etc.
    int process_timeout = 30;         // Seconds to wait for process/window
};

struct MigotoConfig {
    bool use_hook = true;           // true=Hook injection, false=Direct injection
    bool enforce_rendering = true;
    bool enable_hunting = false;
    bool dump_shaders = false;
    bool mute_warnings = true;
    bool calls_logging = false;
    bool debug_logging = false;
    bool unsafe_mode = false;
    int xxmi_dll_init_delay = 500;
};

// Game-specific settings — generic key-value map so any game can use it
// without hardcoding game-specific fields in the bridge binary.
// The frontend populates this with game-specific data.
struct GameSpecificConfig {
    // Flat key-value settings (e.g. "configure_game" -> "true", "unlock_fps" -> "false")
    std::map<std::string, std::string> settings;
    // Nested settings for INI updates (e.g. "perf_tweaks" -> { section -> { key -> value } })
    std::map<std::string, std::map<std::string, std::map<std::string, std::string>>> ini_updates;

    bool get_bool(const std::string& key, bool default_val = false) const;
    int get_int(const std::string& key, int default_val = 0) const;
    double get_double(const std::string& key, double default_val = 0.0) const;
    std::string get_string(const std::string& key, const std::string& default_val = "") const;
};

// d3dx.ini configuration mappings — driven entirely by config JSON
// Structure: setting_name -> { section -> { option -> value_or_on_off_map } }
struct D3dxIniValue {
    bool is_toggle = false;         // true = has on/off variants
    std::string constant_value;     // used when is_toggle=false
    std::string on_value;           // used when is_toggle=true and setting is ON
    std::string off_value;          // used when is_toggle=true and setting is OFF
};

struct D3dxIniConfig {
    // setting_name -> { section_name -> { option_name -> D3dxIniValue } }
    std::map<std::string, std::map<std::string, std::map<std::string, D3dxIniValue>>> settings;
};

struct SignaturesConfig {
    std::string xxmi_public_key;    // Base64-encoded DER ECDSA P-384 public key
    std::map<std::string, std::string> deployed_migoto_signatures; // dll_name -> base64_sig
};

struct ExtraLibrariesConfig {
    bool enabled = false;
    std::vector<std::wstring> paths;
};

struct ShellCommandConfig {
    bool enabled = false;
    std::string cmd;
    bool wait = true;
};

struct CustomLaunchConfig {
    bool enabled = false;
    std::string cmd;
    std::string inject_mode;        // "Hook", "Inject", "Bypass"
};

struct JadeiteConfig {
    bool enabled = false;
    std::wstring exe_path;          // Full Wine path to jadeite.exe
};

struct BridgeConfig {
    std::string importer;           // Importer name: "WWMI", "SRMI", "ZZMI", "EFMI", etc.
    PathsConfig paths;
    GameConfig game;
    MigotoConfig migoto;
    GameSpecificConfig game_specific;
    D3dxIniConfig d3dx_ini;
    SignaturesConfig signatures;
    ExtraLibrariesConfig extra_libraries;
    CustomLaunchConfig custom_launch;
    ShellCommandConfig pre_launch;
    ShellCommandConfig post_load;
    JadeiteConfig jadeite;          // Anti-cheat bypass for miHoYo games on Linux

    // Load from a JSON file path. All values come from the file; nothing is hardcoded.
    static BridgeConfig load(const std::wstring& json_path);
};

} // namespace bridge
